In [1]:
from rotulos import Rotulos

In [2]:
class Musica:
    def __init__(self, path):
        self.path = path
        self.conteudo = self.path.read_text()
    
    @property
    def rotulos(self):
        linha_rotulos = self._linha_rotulos()

        return [r.strip() for r in linha_rotulos.replace('Rótulos: ', '').split(';') if r.strip() != '']

    def _linha_rotulos(self):
        linha_rotulos = next((l for l in self.conteudo.splitlines() if l.startswith('Rótulos: ')), None)
    
        if linha_rotulos is None:
            raise ValueError(f'{self.path} - Arquivo sem linha de rótulos')

        return linha_rotulos
    
    @rotulos.setter
    def rotulos(self, novos_rotulos):
        nova_linha_rotulos = 'Rótulos: ' + '; '.join(novos_rotulos)

        self.conteudo = self.conteudo.replace(self._linha_rotulos(), nova_linha_rotulos)
        self.path.write_text(self.conteudo)

    def validar_rotulos(self):
        try:
            Rotulos.validar_rotulos(self.rotulos)
        except ValueError as e:
            raise ValueError(f"Música {self.id_musica}: {e}")

In [3]:
from pathlib import Path
import pandas as pd

musicas = []

for file in Path('../../dados/musicas').glob('*.txt'):
    musica = Musica(file)
    rotulos = musica.rotulos

    erros = []
    try:
        musica.validar_rotulos()
    except Exception as e:
        erros.append(str(e))

    musicas.append([musica.path.name, rotulos, erros])

musicas = pd.DataFrame(musicas, columns=['arquivo', 'rotulos', 'erros'])

In [4]:
print('Musicas com erros de rótulos:')
musicas_exploded = musicas.explode('erros')
musicas_exploded.groupby('erros').size().sort_values(ascending=False)

Musicas com erros de rótulos:

Series([], dtype: int64)

In [5]:
#musicas.explode('rotulos').groupby('rotulos').count().sort_values(by='arquivo', ascending=False)
print('Músicas sem rótulos:')
musicas[musicas['rotulos'].apply(lambda x: len(x) == 0)]

Músicas sem rótulos:

       arquivo rotulos erros
5     3678.txt      []    []
7      289.txt      []    []
9      504.txt      []    []
15     510.txt      []    []
17     538.txt      []    []
...        ...     ...   ...
2396   521.txt      []    []
2397   509.txt      []    []
2402  3675.txt      []    []
2404   290.txt      []    []
2410  2543.txt      []    []

[656 rows x 3 columns]

In [ ]:
caminho_arquivo = 'example.csv'
data = pd.read_csv(caminho_arquivo, dtype={'indice_geral': str})
data

,indice,indice_geral,Nome,Letra,Compositor,Letrista,Musicista,Parte,A,B,C,D,Momento,Calendário,Outros,Ignorar,Nota,Youtube,App
0,1,2896,Eis que de longe vem o Senhor,"**Eis que de longe vem o Senhor,\npara as naçõ...",Reginaldo Veloso,NaN,NaN,Tempo Litúrgico,1. Ciclo de Natal,I - Advento,A - Abertura,NaN,Entrada,Advento,NaN,NaN,Gm,https://www.youtube.com/watch?v=5pfotPxxXQY,Índice: 2896\nTítulo: Eis que de longe vem o S...
1,2,2245,"Quando virá, Senhor",NaN,NaN,NaN,NaN,Tempo Litúrgico,1. Ciclo de Natal,I - Advento,A - Abertura,NaN,Entrada,Advento,NaN,NaN,Cm,NaN,"Índice: 2245\nTítulo: Quando virá, Senhor\nRót..."
2,3,709,"Senhor, Vem Salvar",NaN,NaN,NaN,NaN,Tempo Litúrgico,1. Ciclo de Natal,I - Advento,A - Abertura,NaN,Entrada,Advento,NaN,NaN,Em,NaN,"Índice: 709\nTítulo: Senhor, Vem Salvar\nRótul..."
3,4,2897,Alegrai-vos,"**Alegrai-vos: Ele está bem perto,\nSim, alegr...",NaN,NaN,"Josef Gelineau, SJ",Tempo Litúrgico,1. Ciclo de Natal,I - Advento,A - Abertura,NaN,Entrada,Advento,NaN,NaN,D,https://www.youtube.com/watch?v=3KT5DpJXrk8,Índice: 2897\nTítulo: Alegrai-vos\nRótulos: \n...
4,5,2898,"Oh, vinde, enfim, eterno Deus","Ó, Vinde, Enfim, Eterno Deus!\n\n1, Oh! Vinde,...",NaN,NaN,Melodia do século XVII,Tempo Litúrgico,1. Ciclo de Natal,I - Advento,A - Abertura,NaN,Entrada,Advento,NaN,NaN,Cm,https://youtu.be/oUnpHNo4EFM,"Índice: 2898\nTítulo: Oh, vinde, enfim, eterno..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1159,1120r,3447,Se alguém quer me servir,"Se alguém me quer servir,\nse alguém me quer s...","Frei Telles Ramon, O. de M.",NaN,NaN,Cantos para Diversas Circunstâncias,XI. Refrãos orantes,NaN,NaN,NaN,Refrão Meditativo,NaN,NaN,"CD-010094 Chamaste-me, Senhor\nPAULUS\n",D,https://youtu.be/jyNA9ZlOQV0,Índice: 3447\nTítulo: Se alguém quer me servir...
1160,1120s,3448,A glória de meu Pai,|:A glória de meu Pai\né que muitos frutos dei...,"Frei Décio Pacheco Bezerra, OFMCap",NaN,NaN,Cantos para Diversas Circunstâncias,XI. Refrãos orantes,NaN,NaN,NaN,Refrão Meditativo,NaN,NaN,"CD-010094 Chamaste-me, Senhor\nPAULUS\n",E,https://youtu.be/4AR9K5hW6ck,Índice: 3448\nTítulo: A glória de meu Pai\nRót...
1161,1120t,3709,Sede santos!,Como é Santo aquele que chamou a vós!\nSede sa...,"Frei Telles Ramon, O. de M.",NaN,NaN,Cantos para Diversas Circunstâncias,XI. Refrãos orantes,NaN,NaN,NaN,Refrão Meditativo,NaN,NaN,"CD-010094 Chamaste-me, Senhor\nPAULUS\n",D,https://youtu.be/Wu8c1Ryy6jM,Índice: 3709\nTítulo: Sede santos!\nRótulos: \...
1162,1120u,3449,Deus nos criou por seu amor,Deus nos criou por seu amor.\nEle sabe o que é...,NaN,Frase de Dom Luciano Mendes,"Frei Telles Ramon, O. de M.",Cantos para Diversas Circunstâncias,XI. Refrãos orantes,NaN,NaN,NaN,Refrão Meditativo,NaN,NaN,"CD-010094 Chamaste-me, Senhor — PAULUS",G,https://youtu.be/QNxWGCyq9io,Índice: 3449\nTítulo: Deus nos criou por seu a...
1163,1120v,3450,"Eis-me aqui, ó Deus","Eis-me aqui, ó Deus\neis-me aqui, ó Deus\npara...","Frei Décio Pacheco Bezerra, OFMCap",NaN,NaN,Cantos para Diversas Circunstâncias,XI. Refrãos orantes,NaN,NaN,NaN,Refrão Meditativo,NaN,NaN,"CD-010094 Chamaste-me, Senhor — PAULUS",D,https://youtu.be/NcL7NWyXnR8,"Índice: 3450\nTítulo: Eis-me aqui, ó Deus\nRót..."

In [7]:
def atualizar_arquivo(serie, indice_arquivo='indice_geral', colunas=['Momento', 'Calendário', 'Outros']):
    rotulos = []

    for coluna in colunas:
        rotulos += serie[coluna].split(';') if pd.notna(serie[coluna]) else []

    rotulos = [r.strip() for r in rotulos]

    if rotulos == []:
        return

    if len(set(rotulos) - Rotulos.rotulos_possiveis) > 0:
        raise ValueError(f'{serie[indice_arquivo]} - Rótulos inválidos: {set(rotulos) - Rotulos.rotulos_possiveis}')

    try:
        musica = Musica(Path(f'../../dados/musicas/{serie[indice_arquivo]}.txt'))
    except Exception as e:
        print(f'Erro ao abrir arquivo {serie[indice_arquivo]}: {e}')
        return
   
    rotulos_cadastrados = musica.rotulos
    
    rotulos_finais = sorted(set(rotulos_cadastrados) | set(rotulos))

    if len(set(rotulos_finais) - Rotulos.rotulos_possiveis) > 0:
        raise ValueError(f'{serie[indice_arquivo]} - Rótulos inválidos: {set(rotulos_finais) - Rotulos.rotulos_possiveis} - Algum rótulo já cadastrado é inválido.')

    musica.rotulos = rotulos_finais
    
#atualizar_arquivo(data.iloc[0])

data.apply(atualizar_arquivo, axis=1)

Erro ao abrir arquivo -: [Errno 2] No such file or directory: '../../dados/musicas/-.txt'
Erro ao abrir arquivo -: [Errno 2] No such file or directory: '../../dados/musicas/-.txt'
Erro ao abrir arquivo -: [Errno 2] No such file or directory: '../../dados/musicas/-.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo ignorar por letra parecida: [Errno 2] No such file or directory: '../../dados/musicas/ignorar por letra parecida.txt'
Erro ao abrir arquivo o: [Errno 2] No such file or directory: '../../dados/musicas/o.txt'

0       None
1       None
2       None
3       None
4       None
        ...
1159    None
1160    None
1161    None
1162    None
1163    None
Length: 1164, dtype: object