In [1]:
import pandas as pd

similares = pd.read_csv('similares.csv')

In [2]:
similares = similares.sort_values(['similarity', 'reference'], ascending=[False, True])

In [3]:
filtered = similares[similares['similarity'] > .80].copy()

In [4]:
filtered['reference_index'] = filtered['reference'].map(lambda it: int(it.split('-')[0]))
filtered['similar_index'] = filtered['similar'].map(lambda it: int(it.split('-')[0]))

filtered = filtered[filtered['reference_index'] < filtered['similar_index']].copy()

filtered['reference_lyric'] = ''
filtered['similar_lyric'] = ''

In [6]:
#filtered.pivot(index="similar_index", columns=[]).sort_index()

In [8]:
import os
from pathlib import Path
from IPython.display import display

def read_music(index, name):
    path = Path('../dados/musicas') if index <= 612 else Path('../dados/musicas2')
    return (path / name).read_text()

for index in filtered.index:
    filtered.loc[index, 'reference_lyric'] = read_music(filtered.loc[index]['reference_index'], filtered.loc[index]['reference'])
    filtered.loc[index, 'similar_lyric'] = read_music(filtered.loc[index]['similar_index'], filtered.loc[index]['similar'])
    
pd.set_option('display.max_colwidth', int(1e10))
pd.set_option('display.expand_frame_repr', True)

filtered.style.set_properties(**{
    'text-align': 'left',
    'white-space': 'pre-wrap',
})
filtered.to_csv('duplicidades.csv')

In [57]:
####################
# Fix index - First must be 1

# duplicacoes = pd.read_csv('./duplicidades-tratado.csv')
# duplicacoes_identificadas = duplicacoes[duplicacoes['Duplicado'] == True][['reference_index', 'similar_index']]

# indexes = [
#     '../dados/livros/2-Cantando_os_Apelos_da_Eucaristia_-_Volume_III/indice.csv',
#     '../dados/todo/1-Animados pela Fé/index.csv',
#     '../dados/todo/3-Louvemos ao Senhor 2018/index.csv',
#     '../dados/todo/4-Músicas das Campanhas da Fraternidade/index.csv',
# ]

# for index in indexes:
#     content = pd.read_csv(index, index_col=0)    

#     # Fix index: First must be 1
#     content = content.reset_index()
#     content['index'] += 1
#     content = content.set_index('index')

#     content.to_csv(index)

In [3]:
####################
# Drop duplicates

duplicacoes = pd.read_csv('./duplicidades-tratado.csv')
duplicacoes_identificadas = duplicacoes[duplicacoes['Duplicados'] == True][['reference_index', 'similar_index']]

indexes = [
    '../dados/livros/2-Cantando_os_Apelos_da_Eucaristia_-_Volume_III/indice.csv',
    '../dados/livros/1-Animados pela Fé/indice.csv',
    '../dados/todo/3-Louvemos ao Senhor 2018/index.csv',
    '../dados/todo/4-Músicas das Campanhas da Fraternidade/index.csv',
]

for index in indexes:
    content = pd.read_csv(index, index_col=0)

    duplicacoes_do_livro = set(duplicacoes_identificadas['similar_index'])
    musicas_duplicadas = set(content.index) & set(duplicacoes_identificadas['similar_index'])
    
    print(musicas_duplicadas)
    for id in duplicacoes_identificadas[duplicacoes_identificadas.similar_index.isin(musicas_duplicadas)].index:
        reference_index = duplicacoes_identificadas.loc[id]['reference_index']
        similar_index = duplicacoes_identificadas.loc[id]['similar_index']

        content = content.rename(index={similar_index: reference_index})

    content = content.reset_index().drop_duplicates().set_index('index')
    content.to_csv(index)

    print('Duplicações restantes')
    a = content.reset_index().drop_duplicates().groupby('indice').count()
    display(a[a['index']>1])

set()
Duplicações restantes

Empty DataFrame
Columns: [index]
Index: []

set()
Duplicações restantes

Empty DataFrame
Columns: [index]
Index: []

{1480, 1067, 750, 982, 1023}
Duplicações restantes

Empty DataFrame
Columns: [index]
Index: []

{1480}
Duplicações restantes

        index
indice
121         2
128         2
133         2
136         2
140         2
174         2
188         2
30          2
60          2
63          2
78          2